export enum DependencyInjection {
  COURSE_REPOSITORY = 'CourseRepository',
  LESSON_REPOSITORY = 'LessonRepository',
  VIDEO_REPOSITORY = 'VideoRepository',
  CLASS_REPOSITORY = 'ClassRepository',
  CLASS_ASSIGNMENT_REPOSITORY = 'ClassAssignmentRepository',
  COURSE_SCHEDULE_REPOSITORY = 'CourseScheduleRepository',
  ENROLLMENT_REPOSITORY = 'EnrollmentRepository',
  FORM_SUBMISSION_REPOSITORY = 'FormSubmissionRepository',
  INSTRUCTOR_REPOSITORY = 'InstructorRepository',
  PRIVILEGE_REPOSITORY = 'PrivilegeRepository',
  SCHOLARSHIP_REPOSITORY = 'ScholarshipRepository',
  TAG_REPOSITORY = 'TagRepository',
  USER_REPOSITORY = 'UserRepository',
  USER_ASSIGNMENT_REPOSITORY = 'UserAssignmentRepository',
  USER_SCHEDULE_REPOSITORY = 'UserScheduleRepository',
  ATTACHMENT_REPOSITORY = 'AttachmentRepository',
  CATEGORY_REPOSITORY = 'CategoryRepository',
  NOTIFICATION_REPOSITORY = 'NotificationRepository',

  AUTHENTICATION_SERVICE = 'AuthenticationService',
  DYNAMODB_DOCUMENT_CLIENT = 'DynamoDBDocumentClient',
  REDIS_CLIENT = 'RedisClient',

  TAG_CONTEXT = 'TagContext',

  COURSE_CACHE_MEMORY = 'CourseCacheMemory',
  COURSE_REDIS_CACHE_MEMORY = 'CourseRedisCacheMemory',
  ATTACHMENT_CACHE_MEMORY = 'AttachmentCacheMemory',
  ATTACHMENT_REDIS_CACHE_MEMORY = 'AttachmentRedisCacheMemory',
  CATEGORY_CACHE_MEMORY = 'CategoryCacheMemory',
  CATEGORY_REDIS_CACHE_MEMORY = 'CategoryRedisCacheMemory',
  SCHOLARSHIP_CACHE_MEMORY = 'ScholarshipCacheMemory',
  SCHOLARSHIP_REDIS_CACHE_MEMORY = 'ScholarshipRedisCacheMemory',
  TAG_CACHE_MEMORY = 'TagCacheMemory',
  TAG_REDIS_CACHE_MEMORY = 'TagRedisCacheMemory',
}
