export enum DependencyInjection {
  COURSE_REPOSITORY = 'CourseRepository',
  LESSON_REPOSITORY = 'LessonRepository',
  VIDEO_REPOSITORY = 'VideoRepository',
  CLASS_REPOSITORY = 'ClassRepository',
  CLASS_ASSIGNMENT_REPOSITORY = 'ClassAssignmentRepository',
  COURSE_SCHEDULE_REPOSITORY = 'CourseScheduleRepository',
  ENROLLMENT_REPOSITORY = 'EnrollmentRepository',
  FORM_SUBMISSION_REPOSITORY = 'FormSubmissionRepository',
  INSTRUCTOR_REPOSITORY = 'InstructorRepository',
  PRIVILEGE_REPOSITORY = 'PrivilegeRepository',
  SCHOLARSHIP_REPOSITORY = 'ScholarshipRepository',
  TAG_REPOSITORY = 'TagRepository',
  USER_REPOSITORY = 'UserRepository',
  USER_ASSIGNMENT_REPOSITORY = 'UserAssignmentRepository',
  USER_SCHEDULE_REPOSITORY = 'UserScheduleRepository',
  ATTACHMENT_REPOSITORY = 'AttachmentRepository',
  CATEGORY_REPOSITORY = 'CategoryRepository',
  AUTHENTICATION_SERVICE = 'AuthenticationService',
  DYNAMODB_DOCUMENT_CLIENT = 'DynamoDBDocumentClient',

  COURSE_CONTEXT = 'CourseContext',
  SCHOLARSHIP_CONTEXT = 'ScholarshipContext',
  TAG_CONTEXT = 'TagContext',
}
