name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
          cd /home/ec2-user/learning-management-system
          git reset --hard
          git pull origin main
          npm install --production
          npm run build
          export USER_TABLE=${{ secrets.USER_TABLE }}
          export ATTACHMENT_TABLE=${{ secrets.ATTACHMENT_TABLE }}
          export CATEGORY_TABLE=${{ secrets.CATEGORY_TABLE }}
          export CLASS_TABLE=${{ secrets.CLASS_TABLE }}
          export CLASS_ASSIGNMENT_TABLE=${{ secrets.CLASS_ASSIGNMENT_TABLE }}
          export COURSE_TABLE=${{ secrets.COURSE_TABLE }}
          export COURSE_SCHEDULE_TABLE=${{ secrets.COURSE_SCHEDULE_TABLE }}
          export ENROLLMENT_TABLE=${{ secrets.ENROLLMENT_TABLE }}
          export FORM_SUBMISSION_TABLE=${{ secrets.FORM_SUBMISSION_TABLE }}
          export INSTRUCTOR_TABLE=${{ secrets.INSTRUCTOR_TABLE }}
          export LESSON_TABLE=${{ secrets.LESSON_TABLE }}
          export VIDEO_TABLE=${{ secrets.VIDEO_TABLE }}
          export PRIVILEGE_TABLE=${{ secrets.PRIVILEGE_TABLE }}
          export USER_ASSIGNMENT_TABLE=${{ secrets.USER_ASSIGNMENT_TABLE }}
          export SCHOLARSHIP_TABLE=${{ secrets.SCHOLARSHIP_TABLE }}
          export USER_SCHEDULE_TABLE=${{ secrets.USER_SCHEDULE_TABLE }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export COOKIE_SECRET_KEY=${{ secrets.COOKIE_SECRET_KEY }}
          export ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}
          export REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}
          export SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}
          export PORT=${{ secrets.PORT }}
          pm2 stop lms
          pm2 restart ecosystem.config.js
          EOF